// @ts-check
const vscode = require('vscode')
const fs = require('fs')
const path = require('path')

// ─── Schema ───────────────────────────────────────────────────────────────────
// Generated by: npm run schema

/** @type {{ version: number, components: Record<string, ComponentDef>, themes: Record<string, string[]> }} */
const SCHEMA = JSON.parse(fs.readFileSync(path.join(__dirname, 'schema.json'), 'utf-8'))

/**
 * @typedef {{ name: string, type: string, values?: string[], detail: string }} PropDef
 * @typedef {{ container: boolean, props: PropDef[] }} ComponentDef
 */

// ─── Build completion items from schema ───────────────────────────────────────

/** @type {WeakMap<import('vscode').CompletionItem, { insertMode: string, isColor: boolean }>} */
const propMeta = new WeakMap()

/** @param {PropDef} p */
function propToItem(p) {
  const item = new vscode.CompletionItem(p.name, vscode.CompletionItemKind.Property)
  item.detail = p.detail

  if (p.values?.length) {
    item.documentation = new vscode.MarkdownString(p.values.map(v => `- \`${v}\``).join('\n'))
  }

  const insertMode =
    p.type === 'bool'   ? 'bool' :
    p.type === 'number' ? 'number' :
    p.type === 'object' ? 'object' : 'string'

  propMeta.set(item, { insertMode, isColor: p.type === 'color' })
  return item
}

/** @type {Record<string, import('vscode').CompletionItem[]>} */
const COMPONENT_PROPS = Object.fromEntries(
  Object.entries(SCHEMA.components).map(([name, def]) => [name, def.props.map(propToItem)])
)

// ─── Component completion items ───────────────────────────────────────────────

const COMPONENT_ITEMS = Object.entries(SCHEMA.components).map(([name, def]) => {
  const item = new vscode.CompletionItem(name, vscode.CompletionItemKind.Class)
  item.detail = 'frame component'

  if (def.container) {
    item.insertText = new vscode.SnippetString(`${name} $1>\n  $0\n</${name}>`)
  } else if (name === 'Text') {
    item.insertText = new vscode.SnippetString(`${name} $1>$0</${name}>`)
  } else {
    item.insertText = new vscode.SnippetString(`${name} $0 />`)
  }

  return item
})

// ─── Dynamic theme tokens ─────────────────────────────────────────────────────

/** @type {Map<string | null, string[]>} */
const themeTokenCache = new Map()

/** @param {string} source */
function parseTokensFromSource(source) {
  const match = source.match(/tokens\s*:\s*\{([\s\S]+?)\n\s*\}/)
  if (!match) return []
  return [...match[1].matchAll(/^\s{4}(\w+)\s*:/gm)].map(m => `$${m[1]}`)
}

function fallbackTokens() {
  const all = new Set(Object.values(SCHEMA.themes).flat())
  return [...all].map(t => `$${t}`)
}

/** @param {import('vscode').TextDocument} document @returns {Promise<string[]>} */
async function getThemeTokens(document) {
  const fmMatch = document.getText().match(/^---\r?\n([\s\S]*?)\r?\n---/)
  const themeName = fmMatch?.[1].match(/theme:\s*(\S+)/)?.[1] ?? null

  if (themeTokenCache.has(themeName)) {
    return /** @type {string[]} */ (themeTokenCache.get(themeName))
  }

  /** @type {string[]} */
  let tokens = []

  if (themeName) {
    // Bundled themes first
    if (SCHEMA.themes[themeName]) {
      tokens = SCHEMA.themes[themeName].map(t => `$${t}`)
    } else {
      // Search the workspace for a custom theme file
      const files = await vscode.workspace.findFiles(
        `**/themes/${themeName}.{ts,js}`,
        '**/node_modules/**',
        1
      )
      if (files.length) {
        try {
          tokens = parseTokensFromSource(fs.readFileSync(files[0].fsPath, 'utf-8'))
        } catch { /* ignore read errors */ }
      }
    }
  }

  if (!tokens.length) tokens = fallbackTokens()

  themeTokenCache.set(themeName, tokens)
  return tokens
}

// ─── Tag detection ────────────────────────────────────────────────────────────

// Returns the component name when the cursor is inside an unclosed opening tag's
// prop list, e.g. <Stack gap={32} |here>. Returns null for children context.
/** @param {import('vscode').TextDocument} document @param {import('vscode').Position} position */
function getTagAtCursor(document, position) {
  const text = document.getText(new vscode.Range(new vscode.Position(0, 0), position))
  const lastOpen = text.lastIndexOf('<')
  if (lastOpen < 0) return null

  if (text[lastOpen + 1] === '/') return null

  const rest = text.slice(lastOpen + 1)
  const m = rest.match(/^([A-Z][A-Za-z]*)/)
  if (!m) return null

  if (rest.slice(m[1].length).includes('>')) return null

  return m[1]
}

// ─── Completion provider ──────────────────────────────────────────────────────

/** @type {vscode.CompletionItemProvider} */
const provider = {
  async provideCompletionItems(document, position) {
    const prefix = document.lineAt(position).text.slice(0, position.character)

    // 1. After "<": suggest component names
    if (/<\s*$/.test(prefix) || /<[A-Z]\w*$/.test(prefix)) {
      return COMPONENT_ITEMS
    }

    const tag = getTagAtCursor(document, position)
    if (!tag || !COMPONENT_PROPS[tag]) return []

    const props = COMPONENT_PROPS[tag]

    // 2. Inside a string attribute value: suggest enum values or theme tokens
    if (/=\s*"[^"]*$/.test(prefix)) {
      const attrName = prefix.match(/(\w+)\s*=\s*"[^"]*$/)?.[1]
      if (!attrName) return []

      const propDef = props.find(p => p.label === attrName)
      if (!propDef) return []

      const meta = propMeta.get(propDef)

      if (meta?.isColor) {
        const tokens = await getThemeTokens(document)
        return tokens.map(v => {
          const item = new vscode.CompletionItem(v, vscode.CompletionItemKind.Color)
          item.insertText = v
          return item
        })
      }

      if (propDef.documentation instanceof vscode.MarkdownString) {
        const values = (propDef.documentation.value.match(/`([^`]+)`/g) ?? []).map(v => v.slice(1, -1))
        return values.map(v => new vscode.CompletionItem(v, vscode.CompletionItemKind.EnumMember))
      }

      return []
    }

    // 3. Inside an open tag: suggest props
    return props.map(p => {
      const item = new vscode.CompletionItem(p.label, p.kind)
      item.detail = p.detail
      item.documentation = p.documentation

      const meta = propMeta.get(p)
      if (meta?.insertMode === 'bool') {
        item.insertText = new vscode.SnippetString(`${p.label}={true}`)
      } else if (meta?.insertMode === 'string') {
        item.insertText = new vscode.SnippetString(`${p.label}="$1"`)
      } else {
        item.insertText = new vscode.SnippetString(`${p.label}={$1}`)
      }

      return item
    })
  },
}

// ─── Activate ─────────────────────────────────────────────────────────────────

/** @param {import('vscode').ExtensionContext} context */
function activate(context) {
  context.subscriptions.push(
    vscode.languages.registerCompletionItemProvider(
      { language: 'frame', scheme: 'file' },
      provider,
      '<', '"'
    ),
    // Invalidate theme cache when a theme file is saved
    vscode.workspace.onDidSaveTextDocument(doc => {
      if (doc.fileName.includes(`${path.sep}themes${path.sep}`)) {
        themeTokenCache.clear()
      }
    })
  )
}

function deactivate() {}

module.exports = { activate, deactivate }
